### ISSUE TITLE
Information is not fetched

### ISSUE THREAD

**Issue by Melindrea** [ahrefs/ahrefs-api-php#2]
Prior to the summer I wrote code to fetch information from ahref's API using this library. It worked quite well.

However, now the same code does not seem to work at all. Even the basic example of the index.php file (using my token) seems to do nothing. It appears to work, but no information is returned. It's just sitting there.

The token works if I go straight to the API, but not with my code nor the example code from this repository.

**Comment by cyberhuman** [comment]
This issue is fixed in 5411409.
